#!/bin/bash
set -e
set -o pipefail

swiftformat .
./gradlew clean spotlessApply assemble allTests
xcodebuild test \
    -project macOS/Arrivals.xcodeproj \
    -scheme Arrivals \
    -destination 'platform=macOS'
